version: '3.7'
services:
  slim-python:
    container_name: python-3
    build: .
    image: slim/python:latest
    restart: unless-stopped
    working_dir: /usr/src/myapp
    stdin_open: true
    tty: true
    command: python3
    volumes:
      - PythonVol:/usr/src/myapp
volumes:
  PythonVol:
